name: event-receiver
namespace: default
runtime: nodejs18
source:
    sourceType: git
    url: https://github.com/kwiatekus/examples.git
    repository: kyma-examples-repo
    reference: reflect-changes-in-cloudevents-api
    baseDir: /incluster_eventing/src/receiver-fn/
subscriptions:
    - name: event-receiver
      protocol: ""
      filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.acme.payload.sanitised.v1
