run:
  modules-download-mode: readonly
  timeout: 15m
linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unparam
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    #exclude our internal deprecated fields
    - "^SA1019: s.Commit is deprecated:"
    - "^SA1019: m.State.Function.Status.Commit is deprecated:"
