apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    labels:
        app.kubernetes.io/name: event-emitter
    name: event-emitter
    namespace: default
spec:
    runtime: nodejs24
    source:
      gitRepository: 
        url: https://github.com/kyma-project/serverless.git
        baseDir: /examples/incluster_eventing/src/emitter-fn/
        reference: main
    env:
        - name: EVENT_TYPE
          value: payload.sanitised
        - name: EVENT_SOURCE
          value: my-app
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: incoming-http-trigger
  namespace: default
spec:
  hosts:
  - incoming
  service:
    name: event-emitter
    namespace: default
    port: 80
  gateway: kyma-system/kyma-gateway
  rules:
  - path: /*
    methods: ["GET", "POST"]
    noAuth: true
