apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    labels:
        app.kubernetes.io/name: event-receiver
    name: event-receiver
    namespace: default
spec:
    runtime: nodejs20
    source:
      gitRepository: 
        url: https://github.com/kyma-project/serverless.git
        baseDir: /examples/incluster_eventing/src/receiver-fn/
        reference: main
---
apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: event-receiver
  namespace: default
spec:
  sink: 'http://event-receiver.default.svc.cluster.local'
  source: ""
  types:
  - sap.kyma.custom.acme.payload.sanitised.v1
