version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: "^SA1019: m.result.Requeue is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: res.Requeue is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: r.result.Requeue is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: result.Requeue is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: status.RuntimeImageOverride is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: s.instance.Spec.Template is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: s.instance.Spec.Template.Labels is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: function.Status.RuntimeImageOverride is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: status.BuildResourceProfile is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: status.BuildResourceProfile is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: instance.Spec.ResourceConfiguration.Build is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: rc.Build is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: function.Status.BuildResourceProfile is deprecated:"
      - path: (.+)\.go$
        text: "^SA1019: s.instance.Spec.ResourceConfiguration.Build is deprecated:"
      - path: (.+)\.go$
        text: "^QF1008:"
      - path: (.+)\.go$
        text: "^SA1019: result.Requeue is deprecated:"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
