run:
  modules-download-mode: readonly
  timeout: 15m
linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unparam
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    #exclude our internal deprecated fields
    - "^SA1019: status.RuntimeImageOverride is deprecated:"
    - "^SA1019: s.instance.Spec.Template is deprecated:"
    - "^SA1019: s.instance.Spec.Template.Labels is deprecated:"
    - "^SA1019: function.Status.RuntimeImageOverride is deprecated:"
    - "^SA1019: status.BuildResourceProfile is deprecated:"
    - "^SA1019: status.BuildResourceProfile is deprecated:"
    - "^SA1019: instance.Spec.ResourceConfiguration.Build is deprecated:"
    - "^SA1019: rc.Build is deprecated:"
    - "^SA1019: function.Status.BuildResourceProfile is deprecated:"
    - "^SA1019: s.instance.Spec.ResourceConfiguration.Build is deprecated:"
