run:
  timeout: 15m
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
issues:
  exclude:
    #exclude our internal deprecated fields
    - "^SA1019: v1alpha2.Nodejs18 is deprecated:"
    - "^SA1019: serverlessv1alpha2.Nodejs18 is deprecated:"
    - "^SA1019: serverlessv1alpha2.Python39 is deprecated:"
    - "^SA1019: status.RuntimeImageOverride is deprecated:"
    - "^SA1019: s.instance.Spec.Template is deprecated:"
    - "^SA1019: s.instance.Spec.Template.Labels is deprecated:"
    - "^SA1019: function.Status.RuntimeImageOverride is deprecated:"
