name: kyma-project.io/module/serverless
team: kyma/otters-dev
images:
  - europe-docker.pkg.dev/kyma-project/prod/serverless-operator:1.14.1
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs22:1.14.1
  - europe-docker.pkg.dev/kyma-project/restricted-prod/function-runtime-nodejs22-fips:1.14.1
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs24:1.14.1
  - europe-docker.pkg.dev/kyma-project/restricted-prod/function-runtime-nodejs24-fips:1.14.1
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs26:1.14.1
  - europe-docker.pkg.dev/kyma-project/restricted-prod/function-runtime-nodejs26-fips:1.14.1
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-python312:1.14.1
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-python314:1.14.1
  - europe-docker.pkg.dev/kyma-project/restricted-prod/function-runtime-python314-fips:1.14.1
  - europe-docker.pkg.dev/kyma-project/prod/function-buildless-controller:1.14.1
  - europe-docker.pkg.dev/kyma-project/prod/function-buildless-init:1.14.1
