services:
  # serverless
  function_controller:
    image: europe-docker.pkg.dev/kyma-project/dev/function-controller:local
    platform: "linux/amd64"
    build:
      context: components/serverless
      dockerfile: deploy/manager/Dockerfile
  function_webhook:
    image: europe-docker.pkg.dev/kyma-project/dev/function-webhook:local
    platform: "linux/amd64"
    build:
      context: components/serverless
      dockerfile: deploy/webhook/Dockerfile
  function_build_init:
    image: europe-docker.pkg.dev/kyma-project/dev/function-build-init:local
    platform: "linux/amd64"
    build:
      context: components/serverless
      dockerfile: deploy/jobinit/Dockerfile
  function_registry_gc:
    image: europe-docker.pkg.dev/kyma-project/dev/function-registry-gc:local
    platform: "linux/amd64"
    build:
      context: components/serverless
      dockerfile: deploy/registry-gc/Dockerfile

  # runtimes
  function_runtime_nodejs16:
    image: europe-docker.pkg.dev/kyma-project/dev/function-runtime-nodejs16:local
    platform: "linux/amd64"
    build:
      context: components/runtimes/nodejs
      dockerfile: nodejs16/Dockerfile
  function_runtime_nodejs18:
    image: europe-docker.pkg.dev/kyma-project/dev/function-runtime-nodejs18:local
    platform: "linux/amd64"
    build:
      context: components/runtimes/nodejs
      dockerfile: nodejs18/Dockerfile
  function_runtime_python39:
    image: europe-docker.pkg.dev/kyma-project/dev/function-runtime-python39:local
    platform: "linux/amd64"
    build:
      context: components/runtimes/python39
      dockerfile: Dockerfile