module-name: serverless
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/serverless-operator:1.12.0
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs20:1.12.0
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs22:1.12.0
  - europe-docker.pkg.dev/kyma-project/restricted-prod/function-runtime-nodejs22-fips:1.12.0
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-nodejs24:1.12.0
  - europe-docker.pkg.dev/kyma-project/restricted-prod/function-runtime-nodejs24-fips:1.12.0
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-python312:1.12.0
  - europe-docker.pkg.dev/kyma-project/prod/function-runtime-python314:1.12.0
  - europe-docker.pkg.dev/kyma-project/restricted-prod/function-runtime-python314-fips:1.12.0
  - europe-docker.pkg.dev/kyma-project/prod/function-buildless-controller:1.12.0
  - europe-docker.pkg.dev/kyma-project/prod/function-buildless-init:1.12.0
mend:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/test/**"
    - "**/*_test.go"
