kind: ConfigMap
apiVersion: v1
metadata:
  name: functions
  namespace: {{ .Release.Namespace }}
  labels:
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
    kyma-project.io/module: serverless
    app.kubernetes.io/name: serverless
    app.kubernetes.io/instance: serverless-busola-functions
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: busola
    app.kubernetes.io/part-of: serverless
data:
  general: |- {{ (.Files.Get "busola.yaml" | fromYaml).general | toYaml | nindent 4 }}
  details: |- {{ (.Files.Get "busola.yaml" | fromYaml).details | toYaml | nindent 4 }}
  list: |- {{ (.Files.Get "busola.yaml" | fromYaml).list | toYaml | nindent 4 }}
  translations: |- {{ (.Files.Get "busola.yaml" | fromYaml).translations | toYaml | nindent 4 }}
  form: |- {{ (.Files.Get "busola.yaml" | fromYaml).form | toYaml | nindent 4 }}
  dataSources |- {{ (.Files.Get "busola.yaml" | fromYaml).dataSources | toYaml | nindent 4 }}
  presets |- {{ (.Files.Get "busola.yaml" | fromYaml).presets | toYaml | nindent 4 }}
