apiVersion: v1
kind: ConfigMap
metadata:
  name: serverless.function.cli
  namespace: {{ .Release.Namespace }}
  labels:
    kyma-cli/extension: commands
    kyma-cli/extension-version: v1
    kyma-project.io/module: serverless
    app.kubernetes.io/name: serverless
    app.kubernetes.io/instance: serverless-cli-functions
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: cli
    app.kubernetes.io/part-of: serverless
data:
  kyma-commands.yaml: |-
{{ .Files.Get "files/kyma-commands.yaml" | indent 4 }}
