kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: serverless.kyma-project.io--allow-all-egress-from-controllers
spec:
  podSelector:
    matchLabels:
      kyma-project.io/module: serverless
      networking.kyma-project.io/from-serverless: allowed
  policyTypes:
  - Egress
  egress:
    - {}
