apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: buildless-serverless
  name: buildless-serverless-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildless-serverless-leader-election-role
subjects:
  - kind: ServiceAccount
    name: buildless-serverless-controller-manager
    namespace: {{ .Release.Namespace }}
