apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    kyma-project.io/module: serverless
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serverless
    app.kubernetes.io/instance: serverless-leader-election-rolebinding
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: serverless
  name: serverless-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: serverless-leader-election-role
subjects:
  - kind: ServiceAccount
    name: serverless-controller-manager
    namespace: {{ .Release.Namespace }}
