name: function-text2img
namespace: default
runtime: python312
source:
    sourceType: inline
schemaVersion: v0
apiRules:
    - name: function-text2img
      service:
        host: function-text2img
      rules:
        - methods:
            - GET
          accessStrategies:
             - handler: allow
env:
    - name: URL
      valueFrom:
        secretKeyRef:
            name: deepai-secret
            key: URL
    - name: API-KEY
      valueFrom:
        secretKeyRef:
            name: deepai-secret
            key: API-KEY
