name: 'Collect cluster-info'
description: 'Action for collecting cluster-info'

runs:
  using: 'composite'
  steps:
    - name: collect cluster-info
      if: ${{ always() }}
      run: |
        echo "####################"
        echo "kubectl get pods -A"
        echo "####################"
        kubectl get pods -A || true

        echo "########################"
        echo "kubectl get functions -A"
        echo "########################"
        kubectl get functions -A || true

        echo "################################"
        echo "kubectl get serverless -A -oyaml"
        echo "################################"
        kubectl get serverless -A -oyaml || true

        echo "##########################################################"
        echo "Describe serverless operator deploy"
        echo "kubectl describe deploy -A -l app.kubernetes.io/name=serverless-operator"
        echo "##########################################################"
        kubectl describe deploy -A -l app.kubernetes.io/name=serverless-operator || true

        echo "####################################################################"
        echo "Describe serverless controller deploy"
        echo "kubectl describe deploy -A -l app.kubernetes.io/name=serverless"
        echo "####################################################################"
        kubectl describe deploy -A -l app.kubernetes.io/name=serverless || true

        echo "########################################################"
        echo "Serverless controller logs"
        echo "kubectl logs -n kyma-system -l app.kubernetes.io/name=serverless --tail=-1"
        echo "########################################################"
        kubectl logs -n kyma-system -l app.kubernetes.io/name=serverless --tail=-1 || true

        echo "########################################################################################################"
        echo "Serverless operator logs"
        echo "kubectl logs -n kyma-system -l app.kubernetes.io/name=serverless-operator --tail=-1"
        echo "########################################################################################################"
        kubectl logs -n kyma-system -l app.kubernetes.io/name=serverless-operator --tail=-1 || true
      shell: bash
