name: 'Collect cluster-info'
description: 'Action for collecting cluster-info'

runs:
  using: 'composite'
  steps:
    - name: collect cluster-info
      if: ${{ always() }}
      run: |
        echo "####################"
        echo "kubectl get pods -A"
        echo "####################"
        kubectl get pods -A || true

        echo "########################"
        echo "kubectl get functions -A"
        echo "########################"
        kubectl get functions -A || true

        echo "################################"
        echo "kubectl get serverless -A -oyaml"
        echo "################################"
        kubectl get serverless -A -oyaml || true

        echo "##########################################################"
        echo "kubectl describe deploy -n kyma-system serverless-operator"
        echo "##########################################################"
        kubectl describe deploy -n kyma-system serverless-operator || true

        echo "####################################################################"
        echo "kubectl describe deploy -n kyma-system serverless-controller-manager"
        echo "####################################################################"
        kubectl describe deploy -n kyma-system serverless-controller-manager || true

        echo "########################################################"
        echo "kubectl logs -n kyma-system -l app=serverless --tail=-1"
        echo "########################################################"
        kubectl logs -n kyma-system -l app=serverless --tail=-1 || true

        echo "########################################################################################################"
        echo "kubectl logs -n kyma-system -l app.kubernetes.io/component=serverless-operator.kyma-project.io --tail=-1"
        echo "########################################################################################################"
        kubectl logs -n kyma-system -l app.kubernetes.io/component=serverless-operator.kyma-project.io --tail=-1 || true
      shell: bash
