apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        # image: itsthenetwork/nfs-server-alpine:latest
        image: cpuguy83/nfs-server:latest
        # env:
        #   - name: SHARED_DIRECTORY
        #     value: /exports
        args:
        # Pass the paths to share to the Docker image
          - /exports
        ports:
          - name: tcp
            containerPort: 2049
          - name: udp
            containerPort: 111
        securityContext:
          # required! 
          privileged: true
          # alternative...
          # capabilities:
          #   add: ["SYS_ADMIN", "SETPCAP"]
        volumeMounts:
          - mountPath: /exports
            name: mypvc
        resources: {}
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: nfs-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: udp
      port: 111
  selector:
    role: nfs-server