apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.43.157.158
    path: "/"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-test
  template:
    metadata:
      labels:
        role: nfs-test
    spec:
      containers:
      - name: nfs-test
        image: alpine:latest
        command: ["sh", "-c", 'touch /nfs_storage/$(date +"%H_%M_%S"); ls /nfs_storage']
        volumeMounts:
          - mountPath: /nfs_storage
            name: mynfs
        resources: {}
      volumes:
        - name: mynfs
          persistentVolumeClaim:
            claimName: nfs
          # nfs:
          #   server: nfs-server.default.svc.cluster.local
          #   path: "/"
          #   readOnly: false
