# permissions for end users to edit serverlesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serverless-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: serverless-operator
    app.kubernetes.io/part-of: serverless-operator
    app.kubernetes.io/managed-by: kustomize
  name: serverless-editor-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - serverlesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - serverlesses/status
  verbs:
  - get
