# This Makefile is used to add context to the `gardener.mk` file by adding the PROJECT_ROOT variable
# this is needed to use targets in the gardener.mk file from a prompt (e.g. `make -C hack provision-gardener`)

PROJECT_ROOT=..

include ${PROJECT_ROOT}/hack/help.mk
include ${PROJECT_ROOT}/hack/gardener.mk
