name: deploy
on:
  workflow_dispatch:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Kubectl Deployment
        working-directory: k8s-resources
        run: kubectl apply -f .
