# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/serverless.kyma-project.io_functions.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_functions.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_functions.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch
patches:
  - patch: |
      - op: add
        path: "/metadata/labels"
        value: 
          app.kubernetes.io/component: serverless
          app.kubernetes.io/instance: functions.serverless.kyma-project.io
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: functions.serverless.kyma-project.io

commonLabels:
  kyma-project.io/module: serverless
  app.kubernetes.io/name: serverless
  app.kubernetes.io/version: "{{ .Values.global.images.function_controller.version }}"
  app.kubernetes.io/part-of: serverless
  app.kubernetes.io/managed-by: kustomize

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
