apiVersion: operator.kyma-project.io/v1alpha1
kind: Serverless
metadata:
  name: default
  namespace: kyma-system
spec:
  dockerRegistry:
    enableInternal: true
  # very fast git function requeue, useful for tests
  functionRequeueDuration: 10s
