apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "docker-registry.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    {{- include "tplValue" ( dict "value" .Values.global.commonLabels "context" . ) | nindent 4 }}
data:
  config.yml: |-
{{ toYaml .Values.configData | indent 4 }}
