# permissions for end users to view serverlesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serverless-operator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: serverless-operator
    app.kubernetes.io/part-of: serverless-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-viewer-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - serverlesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - serverlesses/status
  verbs:
  - get
