run:
  modules-download-mode: readonly
  timeout: 15m
linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unparam
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    # function for future usage
    - "^func `stopWithErrorOrRequeue` is unused$"
    - "^SA1019: result.DockerRegistry is deprecated:"
    - "^SA1019: spec.TargetCPUUtilizationPercentage is deprecated:"
    - "^SA1019: spec.FunctionBuildExecutorArgs is deprecated:"
    - "^SA1019: spec.FunctionBuildMaxSimultaneousJobs is deprecated:"
    - "^SA1019: spec.DefaultBuildJobPreset is deprecated:"
    - "^SA1019: s.instance.Spec.DockerRegistry is deprecated:"
