run:
  modules-download-mode: readonly
  timeout: 15m
linters:
  disable-all: true
  enable:
    - errcheck
    - copyloopvar
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unparam
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    # function for future usage
    - "^func `stopWithErrorOrRequeue` is unused$"
    - "`shouldPropagateSpecProperties` - `deploymentName` always receives `serverlessDeploymentName`"
    - "`shouldUpdateServerless` - `serverlessName` always receives `serverlessName`"
    - "`shouldPropagateSpecProperties` - `registrySecretName` always receives `serverlessRegistrySecret`"
    - 'secretContainsRequired - result 0 \(bool\) is always false'
    - 'secretContainsSameValues - result 0 \(bool\) is always false'
