// Code generated by mockery v2.53.5. DO NOT EDIT.

package automock

import (
	git "github.com/kyma-project/serverless/components/buildless-serverless/internal/controller/git"
	mock "github.com/stretchr/testify/mock"
)

// AsyncLatestCommitChecker is an autogenerated mock type for the AsyncLatestCommitChecker type
type AsyncLatestCommitChecker struct {
	mock.Mock
}

// CollectOrder provides a mock function with given fields: _a0
func (_m *AsyncLatestCommitChecker) CollectOrder(_a0 string) *git.OrderResult {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CollectOrder")
	}

	var r0 *git.OrderResult
	if rf, ok := ret.Get(0).(func(string) *git.OrderResult); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.OrderResult)
		}
	}

	return r0
}

// MakeOrder provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *AsyncLatestCommitChecker) MakeOrder(_a0 string, _a1 string, _a2 string, _a3 *git.GitAuth) {
	_m.Called(_a0, _a1, _a2, _a3)
}

// NewAsyncLatestCommitChecker creates a new instance of AsyncLatestCommitChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAsyncLatestCommitChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *AsyncLatestCommitChecker {
	mock := &AsyncLatestCommitChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
