// Code generated by mockery v2.53.5. DO NOT EDIT.

package automock

import (
	git "github.com/kyma-project/serverless/components/buildless-serverless/internal/controller/git"
	mock "github.com/stretchr/testify/mock"
)

// AsyncLastCommitChecker is an autogenerated mock type for the AsyncLastCommitChecker type
type AsyncLastCommitChecker struct {
	mock.Mock
}

// DeleteLastCommitCheckOrder provides a mock function with given fields: _a0, _a1, _a2
func (_m *AsyncLastCommitChecker) DeleteLastCommitCheckOrder(_a0 string, _a1 string, _a2 *git.GitAuth) {
	_m.Called(_a0, _a1, _a2)
}

// GetLastCommitCheckResult provides a mock function with given fields: _a0, _a1, _a2
func (_m *AsyncLastCommitChecker) GetLastCommitCheckResult(_a0 string, _a1 string, _a2 *git.GitAuth) *git.OrderResult {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetLastCommitCheckResult")
	}

	var r0 *git.OrderResult
	if rf, ok := ret.Get(0).(func(string, string, *git.GitAuth) *git.OrderResult); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.OrderResult)
		}
	}

	return r0
}

// IsLastCommitCheckOrdered provides a mock function with given fields: _a0, _a1, _a2
func (_m *AsyncLastCommitChecker) IsLastCommitCheckOrdered(_a0 string, _a1 string, _a2 *git.GitAuth) bool {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for IsLastCommitCheckOrdered")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, *git.GitAuth) bool); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrderLastCommitCheck provides a mock function with given fields: _a0, _a1, _a2
func (_m *AsyncLastCommitChecker) OrderLastCommitCheck(_a0 string, _a1 string, _a2 *git.GitAuth) {
	_m.Called(_a0, _a1, _a2)
}

// NewAsyncLastCommitChecker creates a new instance of AsyncLastCommitChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAsyncLastCommitChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *AsyncLastCommitChecker {
	mock := &AsyncLastCommitChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
