// Code generated by mockery v2.46.0. DO NOT EDIT.

package automock

import (
	git "github.com/kyma-project/serverless/internal/controller/git"
	mock "github.com/stretchr/testify/mock"
)

// LastCommitChecker is an autogenerated mock type for the LastCommitChecker type
type LastCommitChecker struct {
	mock.Mock
}

// GetLatestCommit provides a mock function with given fields: url, reference, gitAuth
func (_m *LastCommitChecker) GetLatestCommit(url string, reference string, gitAuth *git.GitAuth) (string, error) {
	ret := _m.Called(url, reference, gitAuth)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCommit")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *git.GitAuth) (string, error)); ok {
		return rf(url, reference, gitAuth)
	}
	if rf, ok := ret.Get(0).(func(string, string, *git.GitAuth) string); ok {
		r0 = rf(url, reference, gitAuth)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, *git.GitAuth) error); ok {
		r1 = rf(url, reference, gitAuth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLastCommitChecker creates a new instance of LastCommitChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLastCommitChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *LastCommitChecker {
	mock := &LastCommitChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
