// Code generated by mockery v2.39.0. DO NOT EDIT.

package automock

import mock "github.com/stretchr/testify/mock"

// LastCommitChecker is an autogenerated mock type for the LastCommitChecker type
type LastCommitChecker struct {
	mock.Mock
}

// GetLatestCommit provides a mock function with given fields: url, reference
func (_m *LastCommitChecker) GetLatestCommit(url string, reference string) (string, error) {
	ret := _m.Called(url, reference)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCommit")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(url, reference)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(url, reference)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(url, reference)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLastCommitChecker creates a new instance of LastCommitChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLastCommitChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *LastCommitChecker {
	mock := &LastCommitChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
