# TODO: remove this target after changing this target on the test-infra side
# https://github.com/kyma-project/test-infra/pull/7183/files
.PHONY: run-manual
run-manual: 
	@make -C ../../common run-without-lifecycle-manager
