apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: kyma-project.io--{{ template "fullname" . }}-allow-registry
  labels:
    {{- include "tplValue" ( dict "value" .Values.global.commonLabels "context" . ) | nindent 4 }}
    purpose: registry
spec:
  podSelector:
    matchLabels:
      kyma-project.io/module: {{ template "fullname" . }}
      app.kubernetes.io/name: docker-registry
  policyTypes:
  - Ingress
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: {{ .Values.global.registryServicePort }}
