kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: kyma-project.io--{{ template "fullname" . }}-allow-egress
  labels:
    {{- include "tplValue" ( dict "value" .Values.global.commonLabels "context" . ) | nindent 4 }}
    purpose: fn-code-fetching
spec:
  podSelector:
    matchLabels:
      kyma-project.io/module: {{ template "fullname" . }}
      networking.serverless.kyma-project.io/from-serverless: allowed
  policyTypes:
  - Egress
  egress:
    - {}
