apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tplValue" ( dict "value" .Values.global.commonLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/instance: {{ template "fullname" . }}-controller-manager-service-account
    app.kubernetes.io/component: {{ template "fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-function
  namespace: {{ .Release.Namespace }}
  labels:
    serverless.kyma-project.io/config: service-account
    {{- include "tplValue" ( dict "value" .Values.global.commonLabels "context" . ) | nindent 4 }}
    app.kubernetes.io/instance: {{ template "fullname" . }}-function-service-account
    app.kubernetes.io/component: {{ template "fullname" . }}
automountServiceAccountToken: false
imagePullSecrets:
  - name: {{ template "fullname" . }}-registry-config-default
