apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-operator
  namespace: kyma-system
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: CHART_PATH
              value: "/buildless-module-chart"
