// Code generated by mockery v2.39.2. DO NOT EDIT.

package automock

import (
	mock "github.com/stretchr/testify/mock"

	v1alpha2 "github.com/kyma-project/serverless/components/serverless/pkg/apis/serverless/v1alpha2"
)

// StatsCollector is an autogenerated mock type for the StatsCollector type
type StatsCollector struct {
	mock.Mock
}

// UpdateReconcileStats provides a mock function with given fields: f, cond
func (_m *StatsCollector) UpdateReconcileStats(f *v1alpha2.Function, cond v1alpha2.Condition) {
	_m.Called(f, cond)
}

// NewStatsCollector creates a new instance of StatsCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsCollector {
	mock := &StatsCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
