name: serverless build (push)

on:
  workflow_call:
  push:
    branches: [ "main", "release-*" ]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    tags:
      - '^v?\d+\.\d+\.\d+(?:-.*)?$'

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  compute-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_tag.outputs.TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the latest tag
        id: get_tag
        run: |
          {
            echo 'TAGS<<EOF'
            echo "${{ github.sha }}"
            echo "${{ github.ref_name}}"
            echo EOF
          } >> "$GITHUB_OUTPUT"

  build-operator:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: serverless-operator
      dockerfile: components/operator/Dockerfile
      tags: ${{ needs.compute-tags.outputs.tags }}

  build-serverless-controller:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-controller
      dockerfile: components/serverless/deploy/manager/Dockerfile
      tags: ${{ needs.compute-tags.outputs.tags }}

  build-serverless-webhook:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-webhook
      dockerfile: components/serverless/deploy/webhook/Dockerfile
      tags: ${{ needs.compute-tags.outputs.tags }}

  build-serverless-jobinit:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-build-init
      dockerfile: components/serverless/deploy/jobinit/Dockerfile
      tags: ${{ needs.compute-tags.outputs.tags }}

  build-nodejs18:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-nodejs18
      dockerfile: nodejs18/Dockerfile
      context: components/runtimes/nodejs
      tags: ${{ needs.compute-tags.outputs.tags }}

  build-nodejs20:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-nodejs20
      dockerfile: nodejs20/Dockerfile
      context: components/runtimes/nodejs
      tags: ${{ needs.compute-tags.outputs.tags }}

  build-python39:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-python39
      dockerfile: python39/Dockerfile
      context: components/runtimes/python
      tags: ${{ needs.compute-tags.outputs.tags }}

  build-python312:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: function-runtime-python312
      dockerfile: python312/Dockerfile
      context: components/runtimes/python
      tags: ${{ needs.compute-tags.outputs.tags }}
