name: Pull integration tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    types: [opened, reopened, synchronize, ready_for_review, converted_to_draft]
    draft: false

jobs:
  operator-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-single-cluster
      - name: run integration test
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: europe-docker.pkg.dev/kyma-project/dev/serverless-operator:PR-${{ github.event.number }}
      - uses: ./.github/actions/collect-cluster-info

  serverless-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-single-cluster
      - name: run integration test
        run: |
          make install-serverless-custom-operator
          make -C tests/serverless serverless-integration serverless-contract-tests
          make remove-serverless
        env:
          IMG: europe-docker.pkg.dev/kyma-project/dev/serverless-operator:PR-${{ github.event.number }}
