name: Pull verify

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

jobs:
  call-operator-verify:
    uses: ./.github/workflows/operator-verify.yaml

  call-serverless-verify:
    uses: ./.github/workflows/serverless-verify.yaml
