name: Pull verify

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

jobs:
  call-unit-tests:
    uses: ./.github/workflows/pull-unit-tests.yaml

  call-integration-tests:
    uses: ./.github/workflows/pull-integration-tests.yaml

